[theme]
primaryColor="#20B2AA"  # Verde agua principal
backgroundColor="#E0F8F7"  # Verde agua claro para el fondo
secondaryBackgroundColor="#AEE8E4"  # Verde agua medio para el fondo secundario
textColor="#2C3E50"  # Gris oscuro para el texto
font="monospace"
